### ISSUE TITLE
Any steps for compiling?

### ISSUE THREAD

**Issue by Skintillion** [deregtd/AC2D#1]

**Comment by deregtd** [comment]
Not that I recall, but if you run into anything funky lemme know and I can help you work through it.

**Comment by Skintillion** [comment]
Guessing this is because of the updates to visual studio...

Below is a link, however after the first 3 the rest are all C2535 errors in xmemory0.

[Errors](http://pastebin.com/tJcAcV3t)

---

Severity    Code    Description Project File    Line    Suppression State
Error   C2535   'IMouseEvents *const *std::allocator<_Ty>::address(IMouseEvents *const &) noexcept const': member function already defined or declared  AC2DTest    c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0 613

---

Warning D9030   '/Gm' is incompatible with multiprocessing; ignoring /MP switch AC2DTest    Z:\Workspaces\Unity\Asheron\AC2D\cl 1  

---

Error   C2338   The C++ Standard forbids containers of const elements because allocator<const T> is ill-formed. AC2DTest    c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0 585

---

Error   C2535   'IWindow *const *std::allocator<_Ty>::address(IWindow *const &) noexcept const': member function already defined or declared    AC2DTest    c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0 613

And thanks for replying! =)

**Comment by deregtd** [comment]
Hah phew.  Okay, I'll give it a shot tonight after work.  Haven't tried compiling it in 2015 yet.

**Comment by Skintillion** [comment]
You don't have to go through all that trouble I'm kinda new to C++ and just checking things out.

**Comment by deregtd** [comment]
Eh, it'd be good to keep it running.  I like dabbling in it periodically, and if I know it's in a working state it's more likely that I'll poke at it again. :)

**Comment by Skintillion** [comment]
Well dang, thanks man! How much of this did you write?

**Comment by deregtd** [comment]
Most of it.  Some of the various format parsing was inspired by code from KewtSquirrel, Pea, and others, a lot of the packet format decoding was shared by all the Decal devs, and I took the newest CRC code from someone's github repo (I forget who it was off the top of my head.)

**Comment by Skintillion** [comment]
Are you Akilla?

**Comment by deregtd** [comment]
Yep.

**Comment by Skintillion** [comment]
Oh well very nice to meet you!

I've known your name for years lol used to play AC a lot

**Comment by deregtd** [comment]
Haha I'm still surprised that anyone knows who the heck I am from the AC era.

**Comment by Skintillion** [comment]
I don't remember WHY i remember it but I definitely came across it many times.

**Comment by deregtd** [comment]
Okay, I committed changes to bring it up to date on VC2015 and build.  You want to use the x64 build now, as the Win32 build probably won't successfully memory map on your OS.  You run it by simply sticking the output file (ac2dtest.exe) into your AC dir, and then edit your launcher.ini to run ac2dtest.exe instead of acclient.exe.  That will get you to the char select screen.  For some reason it isn't entering game, but I'm too tired to figure out why right now.

**Comment by Skintillion** [comment]
You rock thank you so much! ill give it a shot.

**Comment by lolmoney1990** [comment]
I get an error that goes like this
 -a (accountname) -h (FF server IP) -rodat off -glsticket

**Comment by deregtd** [comment]
Oh, I must have left a messagebox in from the debugging.  It's fine, just ignore it.

**Comment by lolmoney1990** [comment]
It then hangs on "Waiting for Connection to Establish"

I can't get past this :(

**Comment by deregtd** [comment]
Not sure then.  You'll have to check with Wireshark to see what's up.  As I left it, I was about to join to char select on WE.  If you have any hope of getting in game, you're going to get used to spending the next 20 hours in front of wireshark and playing with things. :(

If you wait too long before hitting OK then the connection will time out.  You have to connect within like 30 seconds of hitting play from the launcher or your GLSticket times out.

**Comment by lolmoney1990** [comment]
Ah damn, I have no clue how packets work.

Able to give a point in the right direction on how to decode these packets from AC?

**Comment by deregtd** [comment]
If you haven't done any major reverse engineering before, you're probably in way over your head, unfortunately.

You'll have to read through the decoding code in AC2D to see about how the transport header and fragment headers work to assemble game packets, etc.
